apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-maven-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Fonyuy-A/Argocd-for-java-maven-apps
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: webapp 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
